spring:
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creative: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    com:
      journalApp: DEBUG

server:
  port: 8080

springdoc:
  swagger-ui:
    tagsSorter: alpha

ApiKey:
  weather: ${WEATHER_API_KEY}
  quote: ${QUOTE_API_KEY}