import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { ArrowLeft, CalendarDays, Check, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { apiDelete, apiPut } from "@/lib/api";
import { fetchEntryById, fetchOnThisDay } from "@/lib/normalize";
import { fullDate, relativeDay } from "@/lib/dates";
import { moodLabel } from "@/lib/types";
import type { Entry, EntryPayload } from "@/lib/types";

export default function EntryDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const entryQuery = useQuery({ queryKey: ["entry", id], queryFn: () => fetchEntryById(id ?? ""), enabled: Boolean(id) });
  const memoryQuery = useQuery({ queryKey: ["on-this-day", entryQuery.data?.date], queryFn: () => fetchOnThisDay(entryQuery.data?.date ?? ""), enabled: Boolean(entryQuery.data?.date) });
  const [editing, setEditing] = useState(false);
  const [content, setContent] = useState("");
  const [showDelete, setShowDelete] = useState(false);
  useEffect(() => { if (entryQuery.data) setContent(entryQuery.data.content); }, [entryQuery.data]);
  const update = useMutation({ mutationFn: (payload: EntryPayload) => apiPut<Entry>(`/entries/date/${payload.date}`, payload), onSuccess: (data) => { queryClient.setQueryData(["entry", id], data); queryClient.invalidateQueries({ queryKey: ["entries"] }); queryClient.invalidateQueries({ queryKey: ["insights"] }); setEditing(false); } });
  const remove = useMutation({ mutationFn: () => apiDelete<void>(`/entries/${id}`), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["entries"] }); queryClient.invalidateQueries({ queryKey: ["insights"] }); toast("The page is gone.", { description: "What mattered about it stays with you." }); navigate("/app/timeline"); } });
  if (entryQuery.isPending) return <div className="mx-auto max-w-3xl px-5 py-12" data-testid="entry-detail-loading"><div className="h-8 w-48 animate-pulse rounded bg-[var(--sand)]" data-testid="entry-detail-loading-bar" /></div>;
  if (entryQuery.isError || !entryQuery.data) return <div className="mx-auto max-w-3xl px-5 py-16" data-testid="entry-detail-not-found"><p className="eyebrow">A missing page</p><h1 className="display-heading mt-4 text-4xl">This entry wandered off.</h1><Link to="/app/timeline" className="mt-6 inline-flex text-sm font-semibold text-[var(--terracotta)]" data-testid="entry-not-found-back-link">Back to timeline</Link></div>;
  const entry = entryQuery.data;
  const mood = moodLabel(entry.mood);
  return <section className="mx-auto max-w-3xl px-5 py-8 sm:px-8 lg:py-14" data-testid="entry-detail-page"><Link to="/app/timeline" className="inline-flex items-center gap-2 text-sm text-[var(--muted-ink)] transition-colors hover:text-[var(--terracotta)]" data-testid="entry-detail-back-link"><ArrowLeft size={15} /> All pages</Link><header className="mt-12 border-b border-[var(--line)] pb-8" data-testid="entry-detail-header"><p className="eyebrow flex items-center gap-2" data-testid="entry-detail-date"><CalendarDays size={14} /> {relativeDay(entry.date) ? `${relativeDay(entry.date)} · ` : ""}{fullDate(entry.date)}</p><h1 className="display-heading mt-4 text-balance text-[32px] leading-[1.08] sm:text-5xl" data-testid="entry-detail-heading">A page from your life</h1><div className="mt-5 flex flex-wrap items-center gap-3">{mood && <span className="mood-chip" data-testid="entry-detail-mood">{mood.emoji} {mood.label}</span>}{entry.backfilled && <span className="tag-chip-static" data-testid="entry-detail-backfilled">Backfilled page</span>}{entry.tags.map((tag) => <span className="tag-chip-static" key={tag} data-testid={`entry-detail-tag-${tag}`}>#{tag}</span>)}</div></header>{memoryQuery.data && memoryQuery.data.length > 0 && <div className="mt-8 rounded-3xl border border-[var(--terracotta)]/30 bg-[var(--terracotta-soft)] px-6 py-5" data-testid="on-this-day-callout"><p className="eyebrow" data-testid="on-this-day-label">On this day, other years</p><p className="mt-2 font-serif text-lg text-[var(--ink-soft)]" data-testid="on-this-day-copy">You’ve written on this date before. There’s a little more of your story here.</p><div className="mt-4 space-y-3">{memoryQuery.data.slice(0, 3).map((memory) => <Link key={memory.id} to={`/app/entry/${memory.id}`} className="block rounded-2xl border border-[var(--line)] bg-[var(--paper)] px-4 py-3 transition-colors hover:border-[var(--terracotta)]" data-testid={memory.id === memoryQuery.data?.[0]?.id ? "on-this-day-entry-link" : `on-this-day-entry-link-${memory.id}`}><span className="text-xs font-semibold text-[var(--muted-ink)]">{new Date(`${memory.date}T12:00:00`).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}{memory.mood ? ` · ${moodLabel(memory.mood)?.label ?? memory.mood}` : ""}</span><span className="mt-1 line-clamp-2 block font-serif text-[15px] leading-6 text-[var(--ink-soft)]">{memory.content}</span></Link>)}</div></div>}
    <div className="mt-10" data-testid="entry-detail-content">{editing ? <Textarea value={content} onChange={(event) => setContent(event.target.value)} className="min-h-[430px] border-[var(--line)] bg-[var(--paper)] font-serif text-xl leading-9" data-testid="entry-edit-textarea" /> : <div className="drop-cap whitespace-pre-wrap break-words font-serif text-xl leading-[1.75] text-[var(--ink-soft)] sm:text-2xl" data-testid="entry-full-content">{entry.content}</div>}</div><div className="mt-12 flex items-center justify-between border-t border-[var(--line)] pt-5" data-testid="entry-detail-actions"><span className="flex items-center gap-2 text-xs text-[var(--muted-ink)]" data-testid="entry-detail-word-count"><Check size={14} className="text-[var(--sage-deep)]" /> {entry.content.trim().split(/\s+/).filter(Boolean).length} words</span><div className="flex items-center gap-2">{editing ? <><Button variant="ghost" onClick={() => { setEditing(false); setContent(entry.content); }} data-testid="cancel-entry-edit-button">Cancel</Button><Button onClick={() => update.mutate({ date: entry.date, content, mood: entry.mood, tags: entry.tags, backfilled: entry.backfilled })} disabled={update.isPending} className="bg-[var(--terracotta)] text-[var(--on-accent)] hover:bg-[var(--terracotta-deep)] hover:text-[var(--paper)]" data-testid="save-entry-edit-button">{update.isPending ? "Saving…" : "Save edit"}</Button></> : <><Button variant="outline" onClick={() => setEditing(true)} data-testid="edit-entry-button"><Pencil size={15} /> Edit</Button><Button variant="ghost" className="text-[var(--error-text)] hover:bg-[var(--error-bg)]" onClick={() => setShowDelete(true)} data-testid="delete-entry-button"><Trash2 size={15} /> Delete</Button></>}</div></div><Dialog open={showDelete} onOpenChange={setShowDelete}><DialogContent data-testid="delete-entry-dialog"><DialogHeader><DialogTitle data-testid="delete-dialog-title">Let this page go?</DialogTitle><DialogDescription data-testid="delete-dialog-copy">This can’t be undone, and we don’t want you to lose something you meant to keep.</DialogDescription></DialogHeader><DialogFooter><Button variant="ghost" onClick={() => setShowDelete(false)} data-testid="cancel-delete-button">Keep the page</Button><Button variant="destructive" onClick={() => remove.mutate()} disabled={remove.isPending} data-testid="confirm-delete-button">{remove.isPending ? "Deleting…" : "Delete forever"}</Button></DialogFooter></DialogContent></Dialog></section>;
}
